### ISSUE TITLE
getAllFollowers() doesn't add followers to array if less than 100 results

### ISSUE THREAD

**Issue by Wiggen94** [PurpleHorrorRus/simple-helix-api#1] opened 2019-12-17 01:02 UTC
When I try to list the followers of someone with 150 followers, the array length is 200, but only the first 100 is actually in the array. It does work as intended if followers is less than 100 total.

If I try to do it with a channel with 250 viewers the first 200 results is added, but not the last 50.

Also, shouldn't the array be the exact length as followers?

**Comment by PurpleHorrorRus** [comment] 2019-12-17 06:19
Can you write the usernames you checked?

**Comment by Wiggen94** [comment] 2019-12-17 11:52
"jujuu_lol" for instance. I follow that channel, my username is Croome but I can't find my own username or other usernames that followed the channel early on. I think the earliest follows was in the month of August but I can't list any follows from August.

**Comment by PurpleHorrorRus** [comment] 2019-12-17 19:01
Fixed in 1.0.6. Please update via npm. If the problem is solved, please let me know

**Comment by Wiggen94** [comment] 2019-12-17 21:08
Yes it seems to be fixed now! Thank you!

**Closed as completed** 2019-12-17 21:09 UTC
